name: flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  get: ^4.7.2
  iconsax: ^0.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
